version: "2"

run:
  timeout: 5m
  go: "1.22.2"  # Adjust this to your project's Go version
  tests: true

linters:
  enable:
    - bodyclose
    - gosec
    - misspell
    - unconvert
    - whitespace
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gocyclo
    - gocritic
    - godot
    - dogsled
    - dupl
    - contextcheck
    - nilerr
    - prealloc
    - predeclared
    - thelper
    - tparallel

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor$
      - examples$
